[package]
name = "pkgfile_ng"
version = "0.1.0"
edition = "2021"

[dependencies]
cdb = "0.6.0"
tar = { version = "0.4.38", default-features = false }
flate2 = "1.0.25"
unicode-width = "0.1.10"

[profile.release]
opt-level = "s"
lto = true
strip = true
